language: node_js
node_js:
  - '5'
git:
  depth: 3
script:
  - npm run build
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: QL7SOXka980PfvoM4t5Q6qmk3tpvHUpN+3hTzK8vQHooNokwNBHgnkQGrXlfGuPSkYFav+WI5mTTXe71TsZll5ioi1AQ/1XRgs1d7d1VKnRxm6Logd+QvGX121j9UIUBZyn/OIlfDrLts8VyT+hvmhy3dkaY7gMZ7DxLpmD49GRhxMXz7PwUuYCmoGzSGOnq4c9uaoZtil8GaFBYNjVEA+n3bDhNgZ2KomOEbiK4sVuSK80mTaaeZR1rac8jispBvs47JlhhDpyUmY+k6ja2lRmfcCEr/Kq7sGE4/opBrUzKtjv7Ql+J5MraR1h/RAtMjUm/uJDXA8U0axPnRvKNIP0iHZ/NT/QjUY3kYdalw3sbCUZhaSXxvNHxupusvse37pYEjbvaeGS4Zb68zMPcZs+c0kwn249qC6CDoAqUT7QRC6peWc5QZLSZpZQRoVEaHscbZm6Vldb5HWimmsqRhNex3poN+J+FILZvt3s9KvIEggi0sTZDhqHztvn/NBOq404oAuO3Dq3vG7pT2uFM/oWaZ0WyT1UVv9tqTF+mXFXDt6jKWZo1036WyBddZzPjEUyR2KuY3gH6vt3SlOgoC9wricgI9PU7XXlDgxgZETlM/3uq2ZrtIdzym0Ri4yjjPiKWiENKj9z5lmDG4dWIUgcQ9XWsvkCY1LMtq5K17rI=
  app: travel-and-help-ci
  on:
    repo: stremann/travel-and-help-ci