language: node_js
node_js:
  - '5'
deploy:
  provider: heroku
  api_key:
    secure: tRlpaW0vKCGYqJCrHCJ9HOx6f6jZUze3FmssPrIRZfuhBi1AxAfAvAGf3dV1R9I0y3nld7UNvh7jWN24cs0745pF85vonWuMKm0r9Mu54zcAa4zJe/TKiYuaNrBTlXj4ncYne7eDmV28pNtqDAR7KL/CSH1Cp9/2JQGzh2UZD0uauK/ddvqC7klew566oND2k4b81/dJaIJSxeeS4ghOg12XQf5Sfx0A4q53uyDzOCAhlAxaGi/4+fYSPrL6JyVGlTLQM8XhzDech8DxR//TK6vbVMrkwXyIVrz8/xkpfILX5HOXpfhHSTOjzkMkBK4NyTYP9xg3/GEXeDiG7PHSOUyd0xonaazsiJrH1zk1sr1u3I0yqt8x9blZaLSheQAif5Bh1H7LTI/j0SclBzAOiE1pI3g2dQLmftYOH18DbjKyLdISzqrYfecXcZMOXpsJ2QnmDWUkdbUEljMZDanV/BuSybw45eKOafLtvz8HC119PdJpzgW4ncUkjVfF8pGCRqGPKQKM7jBreT4ThiTORoTcs+CRBuN1dfhQA3wJm53ywBcuPKfUSs90tSsu0dqSPaWf12ahnhCvj8Bg5RiAtm56wnQiydYa0SfJDO/q681WHGPZqIFadT/rTqfaqM2l8lnvbS1CvzY/aj2+R9wuytLiEQbCCalMR6J1lfeiKkw=
