language: node_js
cache: node_modules
node_js:
  - '5'
git:
  depth: 5
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: tNjhBzClknPcFacPshFESfYKsIqIm//EOXAbjTFQyaylDEaH7HhpMoooIiTV9orvVD4r5yyajlu/TumVhiXks0+AkJpHBCqVFxtOyn+GxHUUrjlW0T0apaVLyglaFFFIdQStfq03UQSqJJLqtm08Ou7PfPUoIPAV7xngUmyi6r+/Br00I81nsxpvyrjEEmH7cPdVXGPkQHEUMxitriIEe3dhGWYGwpuRWelHwGg4IoMkqKHXjDT68zBjPuJ0bNI79uR4syobIUcKKU1EWB/L76kQD1ud5jWYsM6MhT6lLfOnv4AruvwCEHUhhDdeWPsglF8fYwTk+D4w+QCK5YLEl1IoJ8q512o4EOt/CDQSfMiHb4GbO782kny60B7/SKPnLDA4lsQpT9T6fpXzKvxoXzb5welxoxa77dSFIILYh8GYAJ4IvDTObRsh8eGXsi4V4s06lurk/ar6polEc0k4YBh98KSJGa8PI9+IFANGJV/Jhuf3sKvEgrCPG9v5ebBN/DeByiqGQVuxicSq02uJt12XJ7GJkYjsb14hq5Z4eP0OjJVa8FxTdTuxqNJdYXqGWLk9yQTow7BkElUKxbJ6VxA1/tl/JJhmTNZ/7f9KzAlpibvlAR8GjqiAXG3CQQaHc5qxELD1L5nFx9pNUChi+6rjE1roYcvOw6Q449bTiJQ=
  app: travel-and-help-ci
  on:
    repo: stremann/travel-and-help-ci